version: "3.5"

services:

  spire-agent:
    container_name: spire-agent
    image: spire-agent:simulator
    build:
      context: ./
      dockerfile: Dockerfile
      target: spire-agent
    volumes:
      - simulator-data:/opt/tpm-simulator/.data
    depends_on:
      - spire-server
      - seed
    
  spire-server:
    container_name: spire-server
    image: spire-server:simulator
    build:
      context: ./
      dockerfile: Dockerfile
      target: spire-server
    environment:
      TRUST_DOMAIN: test.local
      REGISTRATION_UDS_PATH: /var/run/spire/spire-registration.sock
    volumes:
      - ./hashes:/opt/spire/.data/hashes

  spire-tools:
    container_name: spire-tpm-pubhash
    image: spire-tpm-pubhash:simulator
    build:
      context: ./
      dockerfile: Dockerfile
      target: spire-tools
    command:
      - "get_tpm_pubhash"
      - "/opt/tpm-simulator/.data"
    volumes:
      - simulator-data:/opt/tpm-simulator/.data
    depends_on:
      - seed      

  seed:
    image: busybox
    container_name: spire-seed
    command:
      - sh
      - -c
      - |
        printf "12345" > /opt/tpm-simulator/.data/seed
    volumes:
      - simulator-data:/opt/tpm-simulator/.data

volumes:
  simulator-data: {}
